# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_in_excel', models.IntegerField(default=0)),
                ('department', models.CharField(default='', max_length=100)),
                ('town', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III')], default='1', max_length=3)),
                ('name', models.CharField(default='', max_length=100)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('x_92', models.FloatField(default=0)),
                ('y_92', models.FloatField(default=0)),
                ('road_technical_class', models.CharField(choices=[('0', 'A'), ('1', 'S')], default='1', max_length=1)),
                ('road_number', models.CharField(default='', max_length=10)),
                ('direction', models.CharField(default='', max_length=100)),
                ('passenger_places', models.IntegerField(default=0)),
                ('free_passenger_places', models.IntegerField(default=0)),
                ('truck_places', models.IntegerField(default=0)),
                ('free_truck_places', models.IntegerField(default=0)),
                ('bus_dedicated_places', models.IntegerField(default=0)),
                ('free_bus_dedicated_places', models.IntegerField(default=0)),
                ('security', models.BooleanField(default=False)),
                ('fence', models.BooleanField(default=False)),
                ('monitoring', models.BooleanField(default=False)),
                ('lighting', models.BooleanField(default=False)),
                ('petrol_station', models.BooleanField(default=False)),
                ('dangerous_cargo_places', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('sleeping_places', models.BooleanField(default=False)),
                ('toilets', models.BooleanField(default=False)),
                ('car_wash', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=9)),
                ('email', models.CharField(default='', max_length=100)),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='mop',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mops_api.Operator'),
        ),
        migrations.AlterUniqueTogether(
            name='mop',
            unique_together=set([('x', 'y', 'name')]),
        ),
    ]
