# Generated by Django 2.0 on 2017-12-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mops_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mop',
            name='operator',
            field=models.ForeignKey(on_delete=None, to='mops_api.Operator'),
        ),
    ]
